spring.application.name=companies-crud

# ===============================
# Configuración de PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/companies
spring.datasource.username=debuggeandoideas
spring.datasource.password=udemy
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# Configuración de JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Pool de Conexiones HikariCP (opcional)
# ===============================
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=20000


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


server.servlet.context-path=/companies-crud